version: '3.2'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp" 
      - "6831:6831/udp" 
      - "6832:6832/udp" 
      - "5778:5778" 
      - "16686:16686" 
      - "14268:14268" 
  hystrix:
    image: arthurtsang/docker-hystrix-dashboard
    ports:
      - "9191:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"